import datetime

AIRPORTS_FILE = 'airports.txt'
PIXEL_PIN = 18
NUM_PIXELS = 50
BRIGHTNESS = 0.5
DAYTIME_DIM_BRIGHTNESS = 0.2
LED_COLOR_ORDER = 'GRB'

# Animation Configuration
WIND_THRESHOLD = 20
WIND_FADE_TIME = 0.5
WIND_PAUSE = 2
ANIMATION_PAUSE = 15
DIM_BRIGHTNESS = 0.02
NUM_STEPS = 100
LIGHTNING_FLASH_COUNT = 3
WEATHER_UPDATE_INTERVAL = 300
WIFI_CHECK_INTERVAL = 300

# Snow animation settings
SNOW_BLINK_COUNT = 3
SNOW_BLINK_PAUSE = 0.4

#Time Variables
LIGHTS_ON_TIME = datetime.time(6, 30)
LIGHTS_OFF_TIME = datetime.time(22, 0)
BRIGHT_TIME_START = datetime.time(7, 0)
DIM_TIME_START = datetime.time(17, 0)

VFR_COLOR = (255, 0, 0)
MVFR_COLOR = (0, 0, 255)
IFR_COLOR = (0, 255, 0)
LIFR_COLOR = (0, 255, 255)
MISSING_COLOR = (165, 255, 0)
LIGHTENING_COLOR = (255, 255, 255)
SNOWY_COLOR = (165, 255, 255)
STALE_DATA_COLOR = (75, 75, 0)
WIFI_DISCONNECTED_COLOR = (0, 75, 0)

#True/False Configuration
WIND_ANIMATION = True
LIGHTENING_ANIMATION = True
SNOWY_ANIMATION = True
DAYTIME_DIMMING = True
ENABLE_LIGHTS_OFF = False
LEGEND = False
ENABLE_HTTPS = False
UPDATE_WEATHER = True
STALE_INDICATION = True
WIFI_INDICATION = True

#Map Settings
MAP_CENTER_LAT = 38.6168
MAP_CENTER_LON = -99.4042
MAP_ZOOM = 4
