import datetime

AIRPORTS_FILE = 'airports.txt'
PIXEL_PIN = "D18"
NUM_PIXELS = 25
BRIGHTNESS = 0.5
DAYTIME_DIM_BRIGHTNESS = 0.3

# Animation Configuration
WIND_THRESHOLD = 20
WIND_FADE_TIME = 0.5
WIND_PAUSE = 1.2
ANIMATION_PAUSE = 5
DIM_BRIGHTNESS = 0.05
NUM_STEPS = 100
LIGHTNING_FLASH_COUNT = 3

# Snow animation settings
SNOW_BLINK_COUNT = 3
SNOW_BLINK_PAUSE = 0.4

#Time Variables
LIGHTS_ON_TIME = datetime.time(7, 0)
LIGHTS_OFF_TIME = datetime.time(9, 55)
BRIGHT_TIME_START = datetime.time(7, 0)
DIM_TIME_START = datetime.time(17, 0)

# Color Definitions in GRB order
VFR_COLOR = (255, 0, 0)
MVFR_COLOR = (0, 0, 255)
IFR_COLOR = (0, 255, 0)
LIFR_COLOR = (0, 255, 255)
MISSING_COLOR = (165, 255, 0)
LIGHTENING_COLOR = (255, 255, 255)

WIND_ANIMATION = True
LIGHTENING_ANIMATION = True
SNOWY_ANIMATION = True
DAYTIME_DIMMING = True
ENABLE_LIGHTS_OFF = True
LEGEND = False
ENABLE_HTTPS = True
